# Generated by Django 4.1.3 on 2022-12-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date',
            new_name='date1',
        ),
    ]
