# Generated by Django 4.1.3 on 2022-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_score_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='ans_time',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='score',
            name='res_rank',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
