# Generated by Django 4.1.3 on 2022-12-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_comment_author_remove_comment_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='client',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
